apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-controller
  namespace: lambda-microservice
  labels:
    app: lambda-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lambda-controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: lambda-controller
    spec:
      containers:
      - name: controller
        image: ${REGISTRY}/lambda-microservice-controller:${TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lambda-db-credentials
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: lambda-redis-credentials
              key: url
        - name: SESSION_EXPIRY_SECONDS
          value: "3600"
        - name: NODEJS_RUNTIME_URL
          value: "http://lambda-nodejs-runtime:8080"
        - name: PYTHON_RUNTIME_URL
          value: "http://lambda-python-runtime:8080"
        - name: RUST_RUNTIME_URL
          value: "http://lambda-rust-runtime:8080"
        - name: RUNTIME_TIMEOUT_SECONDS
          value: "30"
        - name: MAX_SCRIPT_SIZE
          value: "1048576"
        - name: WASM_COMPILE_TIMEOUT_SECONDS
          value: "60"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
