apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: openfaas/gateway:0.24.0
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://faas-netes.openfaas:8080/"
        - name: direct_functions
          value: "true"
        - name: read_timeout
          value: "30s"
        - name: write_timeout
          value: "30s"
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: openfaas
  labels:
    app: gateway
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway
