apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-netes
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faas-netes
  template:
    metadata:
      labels:
        app: faas-netes
    spec:
      containers:
      - name: faas-netes
        image: openfaas/faas-netes:0.14.1
        imagePullPolicy: Always
        env:
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "30s"
        - name: write_timeout
          value: "30s"
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: faas-netes
  namespace: openfaas
  labels:
    app: faas-netes
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: faas-netes
