apiVersion: v1
kind: Secret
metadata:
  name: lambda-db-credentials
  namespace: lambda-microservice
type: Opaque
stringData:
  url: "postgres://postgres:postgres@postgres:5432/lambda_microservice"
---
apiVersion: v1
kind: Secret
metadata:
  name: lambda-redis-credentials
  namespace: lambda-microservice
type: Opaque
stringData:
  url: "redis://redis:6379"
  cache_url: "redis://redis:6379"
