apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: nodejs-runtime
  namespace: openfaas-fn
spec:
  name: nodejs-runtime
  image: ${REGISTRY}/nodejs-runtime:${TAG}
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "10"
  environment:
    LOG_LEVEL: "info"
  limits:
    memory: "256Mi"
    cpu: "100m"
  requests:
    memory: "128Mi"
    cpu: "50m"
  annotations:
    com.openfaas.health.http.path: "/health"
    com.openfaas.health.http.initialDelay: "10s"
    com.openfaas.scale.zero: "false"
